site_name: OpenAEV Documentation
site_description: Documentation about OpenAEV, the next-generation Open Adversary Exposure Validation Platform.
site_author: Filigran
site_url: https://docs.openaev.io
copyright: Â© 2025 Filigran. All rights reserved
repo_name: GitHub
repo_url: https://github.com/OpenAEV-Platform/openaev
edit_uri: https://github.com/OpenAEV-Platform/docs/blob/main/docs/

# Theming
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - announce.dismiss
  palette:
    scheme: filigran
  font:
    text: IBM Plex Sans
    code: Roboto Mono
# CSS
extra_css:
  - assets/css/custom.css

# Extra
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-D12HQ64D7C
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenAEV-Platform
    - icon: fontawesome/solid/book
      link: https://blog.filigran.io
    - icon: fontawesome/brands/slack
      link: https://community.filigran.io
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/filigran
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/FiligranHQ
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/FiligranHQ

# Plugins
plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - search
  - git-committers:
      repository: OpenAEV-Platform/docs
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - glightbox

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: false
      auto_title: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      url_download: true

# Page tree
nav:
  - Home: 'index.md'
  - Deployment & Setup:
    - Platform:
      - Overview: deployment/platform/overview.md
      - Installation: deployment/installation.md
      - Configuration: deployment/configuration.md
      - Authentication: deployment/authentication.md
      - Upgrade: deployment/upgrade.md
    - Ecosystem:
      - Executors: deployment/ecosystem/executors.md
      - Injectors: deployment/ecosystem/injectors.md
      - Collectors: deployment/ecosystem/collectors.md
      - Integration Manager:
          - Overview: deployment/ecosystem/integration-manager/overview.md
          - Quick start: deployment/ecosystem/integration-manager/quick-start.md
          - Installation guide: deployment/ecosystem/integration-manager/installation.md
          - Configuration:
              - Configuration reference : deployment/ecosystem/integration-manager/configuration.md
              - Proxy : deployment/ecosystem/integration-manager/proxy-configuration.md
              - Private Registry : deployment/ecosystem/integration-manager/registry-authentification.md
          - Troubleshooting: deployment/ecosystem/integration-manager/troubleshooting.md
    - Advanced:
      - Platform managers: deployment/managers.md
    - Breaking changes:
      - Index: deployment/breaking-changes.md
      - Migration guides:
        - OpenAEV renaming: deployment/breaking-changes/2.0.0-openaev-renaming.md
  - User Guide:
    - Getting started: usage/getting-started.md
    - Foundations:
      - Scenario and Simulations: usage/scenarios-and-simulations.md
      - Injects and Expectations: usage/injects-and-expectations.md
    - Evaluate your Security posture:
      - Overview: usage/evaluate/overview.md
      - Simulation: usage/simulation.md
      - Atomic testing: usage/atomic.md
      - Injects:
        - Overview: usage/inject-overview.md
        - Inject types: usage/inject-types.md
        - Search and Filter: usage/inject-result-list.md
        - Inject result: usage/inject-result.md
      - Targets: usage/targets.md
      - Expectations: usage/expectations.md
      - Findings: usage/findings.md
      - Dashboards:
        - Custom Dashboards: usage/dashboards/custom-dashboards/custom-dashboards.md
        - Widgets: usage/dashboards/widgets/widgets.md
      - Security Control Validation:
        - Overview: usage/security-control-validation.md
      - Security Coverage enrichment (XTM Suite): usage/xtm-suite-connector.md
    - Build your own Threat Scenario:
      - Scenario: usage/scenario.md
      - Scenario Generation from OpenCTI Security Coverage: usage/scenario/security-coverage.md
      - Default Asset Rules: usage/default-asset-rules.md
      - Importing injects into a Scenario: usage/scenario-import.md
      - Assets: usage/assets.md
      - People: usage/people.md
      - Components:
        - Documents: usage/components/documents.md
        - Custom variables: usage/components/variables.md
        - Channels: usage/components/channels.md
        - Media pressure: usage/components/media-pressure.md
        - Challenges: usage/components/challenges.md
        - Lessons: usage/components/lessons.md
      - Payloads: usage/payloads/payloads.md
    - Share and export:
      - Simulations: usage/simulation-reports.md
      - Notifications: usage/notifications.md
    - Interact with your environment:
      - Injectors:
        - Overview: usage/injectors.md
        - Built-In Injector: usage/injects-builtin.md
        - Caldera Injector: usage/inject-caldera.md
      - Collectors:
        - Overview: usage/collectors.md
      - Agents: usage/openaev-agent.md
    - Rest API: usage/rest-api.md
  - Administration:
    - Introduction: administration/introduction.md
    - Enterprise edition: administration/enterprise.md
    - Platform settings:
      - Parameters: administration/parameters.md
      - Security:
        - Policies: administration/policies.md
        - Users and RBAC: administration/users-and-rbac.md
      - Taxonomies: administration/taxonomies.md
      - XTM Hub: administration/hub.md # Warning: page is linked in XTM Hub documentation
  - Reference:
      - APIs:
          - Filters: reference/apis/filters.md
      - Deployment and stack:
          - Telemetry: reference/deployment/telemetry.md
  - Development:
    - Prerequisites:
      - Ubuntu: development/environment-ubuntu.md
      - Windows: development/environment-windows.md
    - Building and running from source: development/build-from-source.md
    - Platform: development/platform.md
    - Collectors: development/collectors.md
    - Injectors: development/injectors.md
    - REST API: development/api-usage.md
    - Best Practices: development/translations.md



